spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 201610
    url: jdbc:mariadb://localhost:3307/querydsl
  jpa:
    hibernate:
      ddl-auto: create